#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

. `dirname $0`/bigtop.bom

t="scala.version"
find . -name pom.xml -exec sed -i "s#<$t>.*</$t>#<$t>${SCALA_VERSION}</$t>#" {} \;
t="scala.binary.version"
find . -name pom.xml -exec sed -i "s#<$t>.*</$t>#<$t>${SCALA_VERSION%.*}</$t>#" {} \;
t="scala.macros.version"
find . -name pom.xml -exec sed -i "s#<$t>.*</$t>#<$t>2.1.0</$t>#" {} \;
t="spark.version"
find . -name pom.xml -exec sed -i "s#<$t>.*</$t>#<$t>${SPARK_VERSION}</$t>#" {} \;
t="hadoop.version"
find . -name pom.xml -exec sed -i "s#<$t>.*</$t>#<$t>${HADOOP_VERSION}</$t>#" {} \;
t="hbase.version"
find . -name pom.xml -exec sed -i "s#<$t>.*</$t>#<$t>${HBASE_VERSION}</$t>#" {} \;
t="ignite.version"
find . -name pom.xml -exec sed -i "s#<$t>.*</$t>#<$t>${IGNITE_HADOOP_VERSION}</$t>#" {} \;

BUILD_OPTS="-Divy.home=${HOME}/.ivy2 -Dsbt.ivy.home=${HOME}/.ivy2 -Duser.home=${HOME} \
            -Drepo.maven.org=$IVY_MIRROR_PROP \
            -Dreactor.repo=file://${HOME}/.m2/repository \
            -Pscala-${SCALA_VERSION%.*} \
            -Pbuild-distr"
            
if [ "$ZEPPELIN_RUN_TESTS" = "true" ]; then
  BUILD_OPTS="$BUILD_OPTS -DskipTests=false"
else
  BUILD_OPTS="$BUILD_OPTS -DskipTests"
fi

export MAVEN_OPTS="-Xmx1500m -Xms1500m -XX:MaxPermSize=256m"

mvn $BUILD_OPTS clean package
