#!/bin/sh
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

echo "-------------- Knox-do-component-build-started -----------"
#source_file_path=`echo ${base_path%build*}`
#tar_output_folder="${source_file_path}../hdp-output"
#source_file_path=${source_file_path}../HDP_COMPONENT_VARIABLES.sh
#source ${source_file_path}

. `dirname $0`/bigtop.bom

mvn -X -Prelease clean install -DskipTests "$@"

echo;echo
#Copying the knox binary tarball to the hdp-output folder
#cp ${base_path}/knox-ng-dist/target/*${knox_name}*${knox_rpm_version}*bin*.tar.gz ${tar_output_folder}/
#md5sum ${base_path}/knox-ng-dist/target/*${knox_name}*${knox_rpm_version}*bin*.tar.gz
#md5sum ${tar_output_folder}/*${knox_name}*
echo "-------------- Knox-do-component-build-completed --------------"
